### ISSUE TITLE
Clean up overlapping features with the `EditorConfig` package

### ISSUE THREAD

**Issue by mrmeszaros** [jwortmann/ini-syntax#16]
Some package functionality clashes with the `EditorConfig` sublime package:

- both packages provide the syntax highlighting for `.editorconfig` files
  - this creates two `Set Syntax: EditorConfig` entries in the command palette with different highlighting
  - this makes it confusing as hell

- the other package applies the `.editorconig` settings (like `indent_style` or `indent_size`) to Sublime Text
- it has a snippet to generate default configs most projects would use

- however, that package's syntax breaks when using the `A File Icon` package (because it has a hidden INI syntax definition - see here: https://github.com/SublimeText/AFileIcon/issues/71)

- this package provides Key and Value completions for EditorConfig while the other packages does not

This issue spans multiple packages, resolving it would need some cooperation.
I think this is mostly a (dev) user-exprerience issue, however, I see value in having packages playing along and integrating well.

I will link the issue in the other package's tracker once I have created it.

**Comment by jwortmann** [comment]
I'd be willing to remove the syntax and the completion files from this package, but the syntax from the EditorConfig package seems very limited and uses unconventional/wrong scope names. The EditorConfig syntax from here is an extension of the INI syntax, with some addional highlighting for the special keys and values and things like glob expressions. So I think a precondition would be to move the syntax (and perhaps the completion files) to the EditorConfig package, and then it should ideally also be combined into a single syntax file.

In that case I would still add `.editorconfig` to the hidden_file_extensions in the INI syntax from here, because EditorConfig files are just special INI files. And I think I created the EditorConfig syntax when this package was added to Package Control, in order to achieve feature parity with a former INI package, which was replaced by this one. One problem might then be what happens when both packages are installed at the same time, and I assume that it would give precedence to the INI syntax from here by default for `.editorconfig` files, due to Sublime's package load order (alphabetically by package name). But I think it should be possible to override that behavior if the EditorConfig package adds `"extensions": [".editorconfig"]` into the `EditorConfig.sublime-settings` file. I haven't tested this, though.

**Comment by jwortmann** [comment]
I have compiled the EditorConfig syntax from this package into a single file (see below).

So if/after the other package
1. uses this syntax (this means that possible new changes to the INI syntax wouldn't be reflected anymore for the EditorConfig syntax, but actually the INI syntax should be pretty stable, so this is probably not very important)
2. adds `"extensions": [".editorconfig"]` into the settings file
3. creates a new tag for Package Control
4. (optionally) adds the completion files

I could remove the syntax and completion files from this package.

<details open><summary>EditorConfig.sublime-syntax</summary>

```yaml
%YAML 1.2
---
# https://www.sublimetext.com/docs/syntax.html
# https://editorconfig-specification.readthedocs.io/#file-format
name: EditorConfig
scope: source.ini.editorconfig

file_extensions:
  - .editorconfig

contexts:
  main:
    - include: comment
    - include: section
    - include: mapping

  comment:
    - match: ;
      scope: punctuation.definition.comment.ini
      push:
        - meta_scope: comment.line.semicolon.ini
        - match: \n
          pop: true
    - match: \#
      scope: punctuation.definition.comment.ini
      push:
        - meta_scope: comment.line.number-sign.ini
        - match: \n
          pop: true

  section:
    - match: \[
      scope: meta.section.ini punctuation.definition.section.begin.ini
      push:
        - meta_content_scope: meta.section.ini entity.name.section.ini
        - match: \]
          scope: meta.section.ini punctuation.definition.section.end.ini
          pop: true
        - match: \\\S
          scope: constant.character.escape.ini
        - match: /
          scope: punctuation.separator.slash.ini
        - include: glob-expression
        - include: eol-pop

  # https://editorconfig-specification.readthedocs.io/#glob-expressions
  glob-expression:
    - match: '[*?]'
      scope: constant.character.wildcard.ini
    - match: (\[)(!)?\w+(\])
      scope: meta.set.ini
      captures:
        1: punctuation.section.brackets.begin.ini
        2: keyword.operator.logical.ini
        3: punctuation.section.brackets.end.ini
    - match: \{
      scope: punctuation.section.braces.begin.ini
      push:
        - meta_scope: meta.set.ini
        - match: \}
          scope: punctuation.section.braces.end.ini
          pop: true
        - match: \,
          scope: punctuation.separator.sequence.ini
        - match: \.\.
          scope: punctuation.separator.range.ini
        - include: eol-pop

  # https://editorconfig-specification.readthedocs.io/#supported-pairs
  mapping:
    - match: (?=\S)
      push:
        - meta_content_scope: meta.mapping.key.ini
        - match: (?=\s*=)
          set:
            - - meta_content_scope: meta.mapping.ini
              - match: (?=\S)
                set:
                  - mapping-value-meta
                  - mapping-value
              - include: eol-pop
            - - match: =
                scope: punctuation.separator.key-value.ini
                pop: true
        - match: \b(?:indent_style|indent_size|tab_width|end_of_line|charset|trim_trailing_whitespace|insert_final_newline|root)\b
          scope: variable.language.ini
        - include: string
        - include: eol-pop

  mapping-value:
    - match: \b(?i:tab|space|lf|cr(?:lf)?|latin1|utf-8(?:-bom)?|utf-16[bl]e)\b
      scope: support.constant.ini
    - match: \b(?i:true|false)\b
      scope: constant.language.ini
    - include: number
    - include: string
    - include: eol-pop

  mapping-value-meta:
    - meta_scope: meta.mapping.value.ini
    - match: ''
      pop: true

  number:
    - match: '([-+])?\b(\d*(\.)\d+(?:(?:E|e)[-+]?\d+)?)(F|f)?\b'
      scope: meta.number.float.decimal.ini
      captures:
        1: keyword.operator.arithmetic.ini
        2: constant.numeric.value.ini
        3: punctuation.separator.decimal.ini
        4: constant.numeric.suffix.ini
    - match: '([-+])?\b(\d+)\b'
      scope: meta.number.integer.decimal.ini
      captures:
        1: keyword.operator.arithmetic.ini
        2: constant.numeric.value.ini

  string:
    - match: \"
      scope: punctuation.definition.string.begin.ini
      push:
        - meta_scope: string.quoted.double.ini
        - include: character-escape
        - match: \"
          scope: punctuation.definition.string.end.ini
          pop: true
        - match: \n
          pop: true
    - match: \'
      scope: punctuation.definition.string.begin.ini
      push:
        - meta_scope: string.quoted.single.ini
        - include: character-escape
        - match: \'
          scope: punctuation.definition.string.end.ini
          pop: true
        - match: \n
          pop: true
    - match: (?=\S)
      push:
        - meta_content_scope: string.unquoted.ini
        - include: character-escape
        - match: (?=[\s=:,\[])
          pop: true

  character-escape:
    - match: \\(?:[^*\s\w]|[abnrt0]|x\h{4})
      scope: constant.character.escape.ini

  eol-pop:
    - match: $|(?=\s+[;#])
      pop: true
```
</details>
